### ISSUE TITLE
Add more bar chart in  one single VC

### ISSUE THREAD

**Issue by afiq90** [vinicius-a-ro/ios-bar-chart-view#1]
Hey there, thank you for this great bar chart, but currently I need to add 4 bar chart in one single view controller? how can I accomplish this??

**Comment by viniciusaro** [comment]
Hi afiq90. Thanks for reaching out. If you want to show them separately, you just add them as you would add any kind of subviews in you view. The dataSource methods always send the instance of the bar chart as a parameter, so you can differentiate between them and work on each one independently. If you want to display all the data in the same chart, then unfortunately this is not a feature currently implemented.

Hope this have made things more clear.

Thanks.

**Comment by afiq90** [comment]
Thank you, problem solved. :)
